# Generated by Django 4.2.6 on 2023-11-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название юридического лица"
                    ),
                ),
                ("bank_details", models.TextField(verbose_name="Банковские реквизиты")),
            ],
            options={
                "verbose_name": "Клиента",
                "verbose_name_plural": "Клиент",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название товара"),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Высота"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Ширина"
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Длина"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Вес"
                    ),
                ),
                ("arrival_date", models.DateField(verbose_name="Дата поступления")),
                (
                    "contract_number",
                    models.CharField(max_length=100, verbose_name="Номер договора"),
                ),
                (
                    "contract_end_date",
                    models.DateField(verbose_name="Дата окончания договора"),
                ),
                (
                    "position",
                    models.IntegerField(verbose_name="Позиция размещения на стеллаже"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventory.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товар",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Полезный объем"
                    ),
                ),
            ],
            options={
                "verbose_name": "Помещение",
                "verbose_name_plural": "Помещение",
            },
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер")),
                (
                    "storage_capacity",
                    models.IntegerField(verbose_name="Количество мест для хранения"),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Высота"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Ширина"
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Длина"
                    ),
                ),
                (
                    "max_load",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Максимальная нагрузка",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shelves",
                        to="Inventory.product",
                        verbose_name="Список товаров, размещенных на стеллаже",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventory.room",
                        verbose_name="Помещение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стеллаж",
                "verbose_name_plural": "Стеллажи",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="shelf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Inventory.shelf",
                verbose_name="Стеллаж",
            ),
        ),
    ]
