# Generated by Django 4.2.6 on 2023-11-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name_plural": "Клиент"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Товар"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name_plural": "Помещение"},
        ),
        migrations.AlterModelOptions(
            name="shelf",
            options={"verbose_name_plural": "Стеллаж"},
        ),
        migrations.AlterField(
            model_name="client",
            name="bank_details",
            field=models.TextField(verbose_name="Банковские реквизиты"),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Название юридического лица"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="arrival_date",
            field=models.DateField(verbose_name="Дата поступления"),
        ),
        migrations.AlterField(
            model_name="product",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Inventory.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="contract_end_date",
            field=models.DateField(verbose_name="Дата окончания договора"),
        ),
        migrations.AlterField(
            model_name="product",
            name="contract_number",
            field=models.CharField(max_length=100, verbose_name="Номер договора"),
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Высота"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Длина"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="position",
            field=models.IntegerField(verbose_name="Позиция размещения на стеллаже"),
        ),
        migrations.AlterField(
            model_name="product",
            name="shelf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Inventory.shelf",
                verbose_name="Стеллаж",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Вес"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Ширина"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="room",
            name="volume",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Полезный объем"
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="height",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Высота"
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="length",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Длина"
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="max_load",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Максимальная нагрузка"
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="number",
            field=models.IntegerField(verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Inventory.room",
                verbose_name="Помещение",
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="storage_capacity",
            field=models.IntegerField(verbose_name="Количество мест для хранения"),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="width",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Ширина"
            ),
        ),
    ]
