# Generated by Django 4.2.6 on 2023-11-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0002_alter_client_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиента", "verbose_name_plural": "Клиент"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товар"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Помещение", "verbose_name_plural": "Помещение"},
        ),
        migrations.AlterModelOptions(
            name="shelf",
            options={"verbose_name": "Стеллаж", "verbose_name_plural": "Стеллажи"},
        ),
    ]
